{% set version = '2.0.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-visnetwork
  version: {{ version|replace("-", "_") }}

source:
  fn: visNetwork_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/visNetwork_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/visNetwork/visNetwork_{{ version }}.tar.gz
  sha256: bc2e75cf4cc1410d8eb528a38870666117e674f1b9ba5fa1ff769b8ab2e2462f

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, rmarkdown, webshot, igraph, rpart, shiny, shinyWidgets, colourpicker, sparkline, ggraph, flashClust
requirements:
  build:

  host:
    - r-base
    - r-htmltools
    - r-htmlwidgets
    - r-jsonlite
    - r-magrittr

  run:
    - r-base
    - r-htmltools
    - r-htmlwidgets
    - r-jsonlite
    - r-magrittr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('visNetwork')"           # [not win]
    - "\"%R%\" -e \"library('visNetwork')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://datastorm-open.github.io/visNetwork/
  license: MIT + file LICENSE
  summary: Provides an R interface to the 'vis.js' JavaScript charting library. It allows an
    interactive visualization of networks.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: visNetwork
# Title: Network Visualization using 'vis.js' Library
# Version: 2.0.3
# Date: 2018-01-09
# Authors@R: c( person(family = "Almende B.V.", role = c("aut", "cph"), comment = "vis.js library in htmlwidgets/lib, http://visjs.org, http://www.almende.com/home"), person("Benoit", "Thieurmel", role = c("aut", "cre"), comment = "R interface", email = "benoit.thieurmel@datastorm.fr"), person(given = "Titouan", family = "Robert",  email = "titouan.robert@datastorm.fr", role = c("aut", "ctb")) )
# Maintainer: Benoit Thieurmel <benoit.thieurmel@datastorm.fr>
# Description: Provides an R interface to the 'vis.js' JavaScript charting library. It allows an interactive visualization of networks.
# BugReports: https://github.com/datastorm-open/visNetwork/issues
# URL: http://datastorm-open.github.io/visNetwork/
# Depends: R (>= 3.0)
# Imports: htmlwidgets, htmltools, jsonlite, magrittr, utils, methods, grDevices, stats
# License: MIT + file LICENSE
# Suggests: knitr, rmarkdown, webshot, igraph, rpart, shiny, shinyWidgets, colourpicker, sparkline, ggraph, flashClust
# VignetteBuilder: knitr, rmarkdown, webshot
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-01-09 14:56:59 UTC; Datastorm
# Author: Almende B.V. [aut, cph] (vis.js library in htmlwidgets/lib, http://visjs.org, http://www.almende.com/home), Benoit Thieurmel [aut, cre] (R interface), Titouan Robert [aut, ctb]
# Repository: CRAN
# Date/Publication: 2018-01-09 17:25:29 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
