# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Yp/sYLbBYE65T9WYwrrBBvf55P/IWhNSHA2UnEU5eeQFiQ734sBTQDeox+2YqzVXaDF206P6FTcnnlAaghYHKm+VliEotes7D5JgD82zAYIiEWREvb+jM3P2kXtPEjckNLhkMZvMkFkYK4GM/RHv9s4JF9n0dew3Mem+3HVq1xVpFTDRKLD6ck5qWwwQjqhyxMQyqx4Bti8jZ4ZJTVb0ieww5S4pK9gZM3r5xCBcESswNSV/vM5qhFglu5XI+Q80dVpAOQJhmtMl88E73Q7FYHGV0N9aGeElqnZ37P4Bct+ewhdlGWgUomV9UA3sY0gV2ofua/x4WYWR22TdSq2JV0zJR73davttYRmhFUQR2UyCDThIifRM5Wb020K3UKp7O5lbubnN9V32ABa/Rd1RqpESQ/mAXZNh1hzHHuufJyia4F3SFKMZ5s9snbxuwAD4ohiPv8aAkQh6q5c+X6LyMjtZVkGtUhoUqvoLQ5HPGiG0n67L1v6Qn+XEmYKAKnspouFTqbpnp35vOEd4iJaXAbc2FrUHTt/SDB6oVaDBZMULgSdg4wQnlwu7gG4CD6lSUd9GyTCdck5x5A781+RMEIg5/XdtAxjzeC+KcyXvBFhdxq7mEiTFOjq3AZG1Ok9W0EzPyiLwUG/SquiVHbaBGhA++ZqLTOhxpRWEjvybzDs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
