travis:
  secure:
    BINSTAR_TOKEN: SMQhwP3mD8G+u0/lWWsFcAGSTSiSlStlhULKaVgZY5xml39GVvPXCClpsviPacvEsdLsgYIYyfnhEUU5X42gRa+JpZtx9gho9bUYGp7TCcp9DN/9QQI76I9cQrTWlXk353zIIXeWoaFf+fLYMW074KSSZES63ZINK4+xWdbP4F+Pjgoj76aQWETb/jfOXTtqoXGVhLWUqcCz1GSJ0EtaxNd3NqX7mKhbKlT722mI/zaDok5Jwn5Rg5DJ8SiTIgjRJm8vkpE5wPeZriOAv948W2qPK+ejv4BlKn4W+jf8OSZh6ctMSIs495sVzbEneeYCjbmmpqxA+rGBEcbBxQrVCBI7VyqHYEaFcYTulUuGZX2y+z7QzeB7Zjn0tZkQXJWTc0pha6fPREq6ffdOzDpSO8tqep08TzXot+mDd4Sz5ojqMhC7NiYXQUvyJSlFnEmdFKTkNvsq/199Vai/UHH92Mtrq5y492lYT2QDpEh3Vy+6JtahZ51DJLDp7HxFOuR8K/WJWiGipfOGLQv8TLesFjGQqigy0elvoh7Z28mxdO6jlaFUNjZYaDewdiWB8hbxLbvtI0gpyBbbhZ120qQbJMYShtT35fno241j6djc34QzjT9LcLK8HtEut9JzLML/JY3YmQAGqZ2s8CvEnSO778NjjWhrjPfTBL8dRgzYwf4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
