travis:
  secure:
    BINSTAR_TOKEN: BDJ24uE6nB58RVl8G5fl9mOewQR7RxpsDdl/47Ykl/vmpG064OPc/OGURsxEI6iSGKJbyjX7I4gZqypVBCIipOEvPP0UJDJJjrbHDDaz+QKDJF91isBRx57jXJ2Vu3FaNjUkkeik8/7mMOTh0ZEoueVNs3sxIAorQmxaPfz/OGY6TKpHfH2pSE3xd4CGoxrBfyOfvzALWI3U6TJL+RHVdV8itQrCYvAZDlwt+b9FeL572qS0mgRRm+zaKas775xqE1MrK1V+HtQj1iRw55H+WHyleiH5WtUL5jUUQbv0eWNpef3/tBYfULJn87KIoLSZxrVE4HngNu2waNzEJhT8ck26tBtkewdavkOPQ+ZxIBqI+SnxgHdPon+n0HOfRf1bCkj2gh1PqGUdNiwvewu9XIRRMscrBb3mz0j87rJYBnQzf3CcHfI01LYygLKehy7kyFOLFO/3JTwQ00hH0pRxSoL5SiS/y3oDB5rcjJtBbFu/mFYppf6M+aB2jrx5a7bs/+zMUl+BmlWez1GK352t80hNDC5qZaR3s89q88GQUXHsRu0ju43TSlz8MYM2DOeHu3urQBnws53dy97m/PgTMdU8SZn/5Vsvy65FiG9O+HyyFNoPuLslc2PGu2phm3/cXiEGnSAVZKIOg1wdO1HMVp2mDsXA9xzC2MQ79C035DE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
