travis:
  secure:
    BINSTAR_TOKEN: Yp/sYLbBYE65T9WYwrrBBvf55P/IWhNSHA2UnEU5eeQFiQ734sBTQDeox+2YqzVXaDF206P6FTcnnlAaghYHKm+VliEotes7D5JgD82zAYIiEWREvb+jM3P2kXtPEjckNLhkMZvMkFkYK4GM/RHv9s4JF9n0dew3Mem+3HVq1xVpFTDRKLD6ck5qWwwQjqhyxMQyqx4Bti8jZ4ZJTVb0ieww5S4pK9gZM3r5xCBcESswNSV/vM5qhFglu5XI+Q80dVpAOQJhmtMl88E73Q7FYHGV0N9aGeElqnZ37P4Bct+ewhdlGWgUomV9UA3sY0gV2ofua/x4WYWR22TdSq2JV0zJR73davttYRmhFUQR2UyCDThIifRM5Wb020K3UKp7O5lbubnN9V32ABa/Rd1RqpESQ/mAXZNh1hzHHuufJyia4F3SFKMZ5s9snbxuwAD4ohiPv8aAkQh6q5c+X6LyMjtZVkGtUhoUqvoLQ5HPGiG0n67L1v6Qn+XEmYKAKnspouFTqbpnp35vOEd4iJaXAbc2FrUHTt/SDB6oVaDBZMULgSdg4wQnlwu7gG4CD6lSUd9GyTCdck5x5A781+RMEIg5/XdtAxjzeC+KcyXvBFhdxq7mEiTFOjq3AZG1Ok9W0EzPyiLwUG/SquiVHbaBGhA++ZqLTOhxpRWEjvybzDs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
